# 1. ConfigMap for non-sensitive configuration.
# This tells the app how to find the database service.
apiVersion: v1
kind: ConfigMap
metadata:
  name: to-do-app-config
data:
  POSTGRES_HOST: "postgres-service"
---
# 2. Deployment for the main application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app-deployment
  labels:
    app: to-do-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
        - name: to-do-app-container
          image: sumatisinha/to-do-app:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: to-do-app-config
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
---
# 3. Service to expose the to-do-app application
apiVersion: v1
kind: Service
metadata:
  name: to-do-app-service
spec:
  # Use LoadBalancer to expose the service outside of the cluster.
  # On local setups like Docker Desktop, it will use localhost.
  type: LoadBalancer
  ports:
    - port: 80         # The port the service is available on externally
      targetPort: 3000   # The port the container is listening on
  selector:
    app: to-do-app     # This MUST match the labels of your Deployment's pods
